### ISSUE TITLE
Peer-review

### ISSUE THREAD

**Issue by petteri9292** [3nd3r1/protaskinate#5]
- Commitit olivat kuvailevia ja niitä oli usein
- Nimeämiskäytänteet olivat kuvailevia ja docstringit auttoivat koodin lukemisessa
- Tietokannan rakenne on looginen 
- Se mitä tähän mennessä on tuotettu pyörii hyvin ja on mukavan näköinen

En keksinyt valitettavasti mitään moitittavaa. Tähän mennessä erinomaista työtä.

**Comment by 3nd3r1** [comment]
Kiitos palautteesta!
