### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by joonarafael** [3nd3r1/protaskinate#7]
# Vertaisarviointi 2

Repo kloonattu 7.10.

Eritysikiitos `docker compose`n käytöstä!

## Yleistä

Wow, mikä projekti! Sovellus on pitkälti jo tyylitelty ja näyttää upealta.

Sovellus on moitteettomassa kunnossa. Autentikaatio pelittää ja middlewaren hyödyntäminen session tarkistukseen näyttää toimivan hyvin!

Halutessasi voisit lisätä minimivaatimuksia käyttäjänimelle ja salasanalle. Käyttäjänimi `a` & salasana `a` ei ole välttämättä sopivin tunnuspari.

Dashboard ei näytä tekevän mitään, mutta READMEn perusteella se taitaa vain olla vielä 'WIP'. Projektit ja projektien taskit toimivat todella hyvin enkä pienen kokeilun aikana saanut mitään virhetilaa aikaiseksi, joten systeemit taitavat olla pitkälti vesitiiviitä.

Ehdotus: Kun projektiin voi kerran lisätä useita samannimisiä taskeja, pitäisikö tästä kysyä käyttäjältä vahvistusta ("Task named 'x' already exists. Add anyway?")?

Olisin jäänyt toivomaan samanlaista ilmoitusta (kuin "Please log in to access this page.") kun uuden taskin lisää / jotain poistaa jne. Toki listat näyttävät sovelluksessasi päivittyvän reaaliajassa mutta aina onnistuneen (tietokanta)operaation jälkeen on kiva käyttäjänä saada vielä erillinen notification/toast vahvistukseksi.

Repon READMEn mukaan sinulla kuitenkin näyttää riittävän vielä koodattavaa ja muutamia jokseenkin merkittäviäkin toiminnallisuuksia on vielä implementoimatta. Käytähän siis aikasi järkevästi ja jätä minun ehdotukset prioriteettilistalla peräpäähän.

## Koodikanta

Koodi on tasoltaan korkealuokkaista. Vaikea keksiä mitään parannusehdotuksia. Koko projekti on jaettu järkevästi kansioihin ja omiin moduuleihin, eikä millekään jää liian suurta vastuualuetta. Erinomaista!

Python on jaettu loogisiin kokonaisuuksiin ja vieläpä pitkälti abstraktoitu (luokat & niiden inheritance). Jinjan HTML-templateissakin käytät fiksusti `base.html`-filua pohjana.

Tästä on vaikea enää parantaa.

## Skeemasta

Tietokantaskeema näyttää olevan fiksu ja tehokas. Kurssimateriaalissa taidettiin mainita tavoitteeksi 5-10 taulua, mutta ehkä noista tulevista ominaisuuksista, Kanban-dashboardista ja muusta, tulee vielä jokin lisäys. Turhanpäiväinen taulujen jako useampiin olisi toisaalta myös typerää. Sovelluksesi on niin laaja ja samalla niin hyvin toteutettu, ettei tämä taulujen lukumäärästä ole kiinni.

Fiksusti implementoitu (mulla omassa projektissa sama) tuo `updated_at` -triggerifunktio!

## Yhteenveto

Projekti on kerrassaan vaikuttava ja todella upean näköinen. Hieman saattaa tulla kiire aikataulun kanssa, mutta priorisoi tarvittavat ominaisuudet ja implementoi minkä kerkeät. Mitään oikeita virheitä en löydä sovelluksestasi ollenkaan. Hyvää työtä!

**Comment by 3nd3r1** [comment]
Kiitos arvokkaasta palautteesta.

Tuon trigger-idean sain sun projektista 😂
